services:
  tennis-app:
    build: .
    container_name: tennis
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
    volumes:
      - ./db/data:/app/db/data
    restart: unless-stopped
